env:
  global:
    - CIBW_SKIP="cp27-* cp33-* *-manylinux1_i686"
    - TWINE_USERNAME="tlawrence3"

matrix:
  include:
    - dist: trusty
      sudo: required
      language: python
      services:
        - docker
    - os: osx
      osx_image: xcode8.3

install:
# Python 3 is needed to run cibuildwheel.
# Default 2.0.0 Ruby is buggy
# Default bundler version is buggy
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      rvm install ruby-2.3.3;
      rvm --default use 2.3.3;
      brew update;
      brew install python3;
      pip3 install cibuildwheel==0.8.0;
    fi
# Install cibuildwheel using pip3 to make sure Python 3 is used.
  - if [ "${TRAVIS_OS_NAME:-}" == "linux" ]; then
      pip install cibuildwheel==0.8.0;
    fi

script:
  - cibuildwheel --output-dir wheelhouse

  - if [ "${TRAVIS_TAG:-}" != "" ]; then
      python -m pip install twine &&
      python -m twine upload wheelhouse/*;
    fi
