matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
    - language: python

script:
  - export CIBW_SKIP=cp27-*
  - pip3 install cibuildwheel==0.5.0
  - cibuildwheel --output-dir wheelhouse
