matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

language: python

env:
  global:
    - CIBW_SKIP="cp27-* cp33-* *-manylinux1_i686"
script:
  - pip install cibuildwheel==0.5.0
  - cibuildwheel --output-dir wheelhouse
