env:
  global:
    - CIBW_SKIP="cp27-* cp33-* *-manylinux1_i686"
    - TWINE_USERNAME="tlawrence3"

matrix:
  include:
    - dist: trusty
      sudo: required
      language: python
      python: "3.6"
      services: 
        - docker
    - os: osx
      osx_image: xcode8.3

install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      curl -fsSLo /tmp/patch.tar.gz https://github.com/mayeut/patch-macos-python-openssl/releases/download/v0.1.0/patch-macos-python-$PYVER-openssl-v0.1.0.tar.gz;
      sudo tar -C /Library/Frameworks/Python.framework/Versions/$PYVER/ -xmf /tmp/patch.tar.gz;
      rvm install ruby-2.3.3;
      rvm --default use 2.3.3;
      brew update;
      brew upgrade python;
    fi
  - pip3 install --upgrade cibuildwheel
  - touch .cibuildwheel

script:
  - cibuildwheel --output-dir wheelhouse
  - if [ "${TRAVIS_TAG:-}" != "" ]; then
      pip3 install twine;
      python3 -m twine upload --skip-existing wheelhouse/*;
    fi
