matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - export CIBW_SKIP=cp27-*
  - pip install cibuildwheel==0.5.0
  - cibuildwheel --output-dir wheelhouse
