env:
  global:
    - CIBW_SKIP="cp27-* cp33-* cp34-* *-manylinux1_i686"
    - TWINE_USERNAME="tlawrence3"

matrix:
  include:
    - dist: trusty
      sudo: required
      language: python
      python: "3.6"
      services: 
        - docker
    - os: osx
      osx_image: xcode9.3

install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      brew install openssl;
      brew link openssl --force;
      rvm install ruby-2.3.3;
      rvm --default use 2.3.3;
      brew update;
      brew upgrade python --with-brewed-openssl;
    fi
  - pip3 install --upgrade cibuildwheel
  - pip3 install -r requirements.txt
  - touch .cibuildwheel

script:
  - cibuildwheel --output-dir wheelhouse
  - if [ "${TRAVIS_TAG:-}" != "" ]; then
      pip3 install twine;
      python3 -m twine upload --skip-existing wheelhouse/*;
    fi
