env:
  global:
    - CIBW_SKIP="cp27-* cp33-* *-manylinux1_i686"
    - TWINE_USERNAME="tlawrence3"

matrix:
  include:
    - sudo: required
      language: python
      python: 3.4
      services: docker
      env:
        - PYTHON=python
        - PIP=pip
    - os: osx
      env:
        - PYTHON=python3
        - PIP=pip3
      before_install:
              - brew update
              - brew outdated python || brew upgrade python

script:
  - $PIP install cibuildwheel==0.8.0
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      $PYTHON -m pip install twine &&
      $PYTHON -m twine upload wheelhouse/*.whl;
    fi
