env:
  global:
    - CIBW_SKIP="cp27-* cp33-* *-manylinux1_i686"
    - TWINE_USERNAME="tlawrence3"

matrix:
  include:
    - dist: trusty
      sudo: required
      language: python
      env: PYTHON=python3
      services:
        - docker
    - os: osx
      env: PYTHON=python3
      before_install:
              - brew update
              - brew outdated python || brew upgrade python

script:
  - pip install cibuildwheel==0.8.0
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      $PYTHON -m pip install twine &&
      $PYTHON -m twine upload wheelhouse/*.whl;
    fi
