matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

language: python

env:
  global:
    - CIBW_SKIP="cp27-* cp33-*"
script:
  - pip3 install numpy
  - pip3 install statsmodels
  - pip install cibuildwheel==0.5.0
  - cibuildwheel --output-dir wheelhouse
